<?php

declare(strict_types=1);

namespace NeiroNetwork\ExperimentalFeatures\feature\v1_16;

use NeiroNetwork\ExperimentalFeatures\feature\Feature;
use NeiroNetwork\ExperimentalFeatures\feature\interfaces\IBlock;
use pocketmine\block\Block;
use pocketmine\block\BlockBreakInfo;
use pocketmine\block\BlockToolType;
use pocketmine\block\Flowable;
use pocketmine\block\VanillaBlocks;

class NetherSprouts extends Feature implements IBlock{

	public function stringId() : string{
		return "nether_sprouts";
	}

	public function block() : Block{
		return new class(
			$this->blockId(),
			$this->displayName(),
			BlockBreakInfo::instant(BlockToolType::SHEARS, 1)
		) extends Flowable{
			public function canBeReplaced() : bool{
				return true;
			}

			// TODO: 置ける場所を制限する

			public function getFlameEncouragement() : int{
				return parent::getFlameEncouragement(); // TODO: Change the autogenerated stub
			}

			public function getFlammability() : int{
				return parent::getFlammability(); // TODO: Change the autogenerated stub
			}
		};
	}
}
