<?php

declare(strict_types=1);

namespace NeiroNetwork\ExperimentalFeatures\feature\v1_16;

use NeiroNetwork\ExperimentalFeatures\feature\Feature;
use NeiroNetwork\ExperimentalFeatures\feature\interfaces\IBlock;
use pocketmine\block\Block;
use pocketmine\block\BlockBreakInfo;
use pocketmine\block\BlockToolType;
use pocketmine\block\Flowable;
use pocketmine\block\VanillaBlocks;
use pocketmine\item\Item;
use pocketmine\math\Facing;
use pocketmine\math\Vector3;
use pocketmine\player\Player;
use pocketmine\world\BlockTransaction;

class NetherSprouts extends Feature implements IBlock{

	public function stringId() : string{
		return "nether_sprouts";
	}

	public function block() : Block{
		return new class(
			$this->blockId(),
			$this->displayName(),
			BlockBreakInfo::instant(BlockToolType::SHEARS, 1)
		) extends Flowable{
			public function canBeReplaced() : bool{
				return true;
			}

			public function place(BlockTransaction $tx, Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, ?Player $player = null) : bool{
				// TODO: 置ける場所をより正確にする
				if(!$blockReplace->getSide(Facing::DOWN)->isTransparent()){
					return parent::place($tx, $item, $blockReplace, $blockClicked, $face, $clickVector, $player);
				}
				return false;
			}

			public function onNearbyBlockChange() : void{
				if($this->getSide(Facing::DOWN)->isTransparent()){
					$this->position->getWorld()->useBreakOn($this->position);
				}
			}

			public function getFlameEncouragement() : int{
				return parent::getFlameEncouragement(); // TODO: Change the autogenerated stub
			}

			public function getFlammability() : int{
				return parent::getFlammability(); // TODO: Change the autogenerated stub
			}
		};
	}
}
